---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"
  - flowAnimation: &flow-slow
      thresholdOffValue: 2
      thresholdLwrValue: 10
      thresholdLwrDurationSecs: 1
      thresholdUprValue: 100
      thresholdUprDurationSecs: 0.1

#------------------------------------------------------------------------------
# Panel Config

test:
  testDataBaseOffset: 1
  
cellIdPreamble: "cell-"
gradientMode: "hue"
cells: 
  drawio:
    link:
      url: "https://app.diagrams.net/?p=svgdata"
  LoadBalancer:
    dataRef: "test-data-large-sin"
    label:
      separator: "cr"
      units: "none"
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "green", level: 0}
        - {color: "orange", level: 500}
        - {color: "red", level: 1000}
    link: *grafana-home
  lb_wd0019371:
    dataRef: "test-data-large-cos"
    label:
      separator: "cr"
      units: "ops"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "orange", level: 400}
        - {color: "red", level: 800}
    link: *grafana-home
  lb_wd0019372:
    dataRef: "test-data-large-cos"
    label:
      separator: "cr"
      units: "ops"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "orange", level: 400}
        - {color: "red", level: 800}
    link: *grafana-home
  wd0019371:
    dataRef: "test-data-small-cos"
    label:
      separator: "cr"
      units: "none"
    labelColor:
      thresholds:
        - {color: "#888888", level: 0}
        - {color: "light-blue", level: 100}
  wd0019372:
    dataRef: "test-data-small-cos"
    label:
      separator: "cr"
      units: "none"
    labelColor:
      thresholds:
        - {color: "#888888", level: 0}
        - {color: "light-blue", level: 100}
