---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"
  - flowAnimation: &flow-slow
      thresholdOffValue: 1
      thresholdLwrValue: 2
      thresholdLwrDurationSecs: 1
      thresholdUprValue: 100
      thresholdUprDurationSecs: 1

zoomPanPinch:
  # This optional term defines the array of keys that can be used to enable wheel zoom. There's
  # a clash of interest between panel zoom and dashboard scrolling which is easy to avoid with small
  # SVGs, but becomes more problematic when the SVG is large and covers a lot of the screen. By
  # requiring a combo such as ALT+Scroll this clash can be avoided. 
  wheelActivationKeys: ["Alt"]

#------------------------------------------------------------------------------
# Panel Config

datapoint: "last"

test:
  testDataBaseOffset: 1
  
cellIdPreamble: "cell-"
cells: 
  LoadBalancer:
    dataRef: "test-data-large-cos"
    label:
      separator: "cr"
      units: "none"
    labelColor:
      thresholds:
        - {color: "green", level: 0}
        - {color: "orange", level: 500}
        - {color: "red", level: 1000}
  lb_wd0019371:
    dataRef: "test-data-large-cos"
    flowAnimation: *flow-slow
  lb_wd0019372:
    dataRef: "test-data-large-cos"
    flowAnimation: *flow-slow
  wd0019371:
    dataRef: "200"
    link: 
      url: "https://arguspreprod.grafana.net/d/Mofp2p5/em-testing-copy?orgId=1&from=now-3h&to=now&timezone=browser&var-instance=wd-0019371&var-Filters="
    label:
      separator: "cr"
      units: "none"
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "green", level: 4}
  wd0019372:
    dataRef: "503"
    link: 
      url: "https://arguspreprod.grafana.net/d/Mofp2p5/em-testing-copy?orgId=1&from=now-3h&to=now&timezone=browser&var-instance=wd-0019372&var-Filters="
    label:
      separator: "cr"
      units: "none"
    labelColor:
      thresholds:
        - {color: "red", level: 0}
        - {color: "green", level: 4}
